name : hello

on:
  push:
  workflow_dispatch: 
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: word
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{inputs.greeting}}"
      